# Generated by Django 6.0.4 on 2026-05-12 06:03

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieu_de', models.CharField(max_length=255)),
                ('anh_bia', models.URLField(max_length=500)),
                ('trang_thai', models.CharField(choices=[('PENDING', 'Pending'), ('PUBLIC', 'Public')], default='PENDING', max_length=10)),
                ('ngay_phat_hanh', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_album',
            },
        ),
        migrations.CreateModel(
            name='NgheSi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_nghe_si', models.CharField(max_length=150)),
                ('tieu_su', models.TextField(blank=True, null=True)),
                ('anh_nghe_si', models.URLField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'tbl_nghe_si',
            },
        ),
        migrations.CreateModel(
            name='TheLoai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_the_loai', models.CharField(max_length=100)),
                ('mo_ta_the_loai', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_the_loai',
            },
        ),
        migrations.CreateModel(
            name='NguoiDung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('anh_dai_dien', models.URLField(default='def.jpg', max_length=500)),
                ('vai_tro', models.CharField(choices=[('USER', 'User'), ('ADMIN', 'Admin')], default='USER', max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'tbl_nguoi_dung',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BaiHat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieu_de', models.CharField(max_length=255)),
                ('duong_dan_am_thanh', models.URLField(max_length=500)),
                ('duong_dan_hinh_anh', models.URLField(max_length=500)),
                ('luot_nghe', models.IntegerField(default=0)),
                ('quoc_gia', models.CharField(blank=True, max_length=50, null=True)),
                ('nam_phat_hanh', models.IntegerField(blank=True, null=True)),
                ('trang_thai', models.CharField(choices=[('PENDING', 'Pending'), ('PUBLIC', 'Public')], default='PENDING', max_length=10)),
                ('id_album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bai_hats', to='api.album')),
                ('id_nguoi_dang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bai_hats_da_dang', to=settings.AUTH_USER_MODEL)),
                ('id_nghe_si', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bai_hats', to='api.nghesi')),
                ('id_the_loai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bai_hats', to='api.theloai')),
            ],
            options={
                'db_table': 'tbl_bai_hat',
            },
        ),
        migrations.CreateModel(
            name='BaoCao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ly_do', models.TextField()),
                ('trang_thai_xu_ly', models.CharField(choices=[('WAITING', 'Waiting'), ('DONE', 'Done')], default='WAITING', max_length=10)),
                ('ngay_bao_cao', models.DateTimeField(auto_now_add=True)),
                ('id_bai_hat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bi_bao_caos', to='api.baihat')),
                ('id_nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bao_caos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_bao_cao',
            },
        ),
        migrations.CreateModel(
            name='DanhSachPhat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieu_de', models.CharField(max_length=255)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('bai_hats', models.ManyToManyField(db_table='tbl_chi_tiet_playlist', related_name='playlists', to='api.baihat')),
                ('id_chu_so_huu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_danh_sach_phat',
            },
        ),
        migrations.CreateModel(
            name='LichSuNghe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoi_gian_nghe', models.DateTimeField(auto_now_add=True)),
                ('id_bai_hat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_su_nghe', to='api.baihat')),
                ('id_nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_su_nghe', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_lich_su_nghe',
            },
        ),
        migrations.AddField(
            model_name='album',
            name='id_nghe_si',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='api.nghesi'),
        ),
        migrations.CreateModel(
            name='TinNhan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noi_dung', models.TextField()),
                ('thoi_gian_gui', models.DateTimeField(auto_now_add=True)),
                ('id_nguoi_gui', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tin_nhan_gui', to=settings.AUTH_USER_MODEL)),
                ('id_nguoi_nhan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tin_nhan_nhan', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_tin_nhan',
            },
        ),
        migrations.CreateModel(
            name='YeuThich',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_thich', models.DateTimeField(auto_now_add=True)),
                ('id_bai_hat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duoc_yeu_thich', to='api.baihat')),
                ('id_nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yeu_thich', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_yeu_thich',
                'unique_together': {('id_nguoi_dung', 'id_bai_hat')},
            },
        ),
    ]
