# Generated by Django 6.0.4 on 2026-05-12 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baihat',
            name='loi_bai_hat',
            field=models.TextField(blank=True, null=True),
        ),
    ]
