# Generated by Django 6.0.4 on 2026-05-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_baihat_loi_bai_hat'),
    ]

    operations = [
        migrations.AddField(
            model_name='theloai',
            name='anh_the_loai',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
