# Generated by Django 6.0.4 on 2026-05-18 00:01

from django.db import migrations, models


def copy_song_artists_forward(apps, schema_editor):
    BaiHat = apps.get_model('api', 'BaiHat')

    for song in BaiHat.objects.select_related('id_nghe_si').all():
        if song.id_nghe_si_id:
            song.cac_nghe_si.add(song.id_nghe_si_id)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_theloai_anh_the_loai'),
    ]

    operations = [
        migrations.AddField(
            model_name='baihat',
            name='cac_nghe_si',
            field=models.ManyToManyField(db_table='tbl_bai_hat_nghe_si', related_name='bai_hats', to='api.nghesi'),
        ),
        migrations.RunPython(copy_song_artists_forward, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='baihat',
            name='id_nghe_si',
        ),
    ]
