# Generated by Django 6.0.4 on 2026-05-19 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_song_multiple_artists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baihat',
            name='id_the_loai',
        ),
        migrations.AddField(
            model_name='baihat',
            name='the_loais',
            field=models.ManyToManyField(blank=True, db_table='tbl_bai_hat_the_loai', related_name='bai_hats', to='api.theloai'),
        ),
    ]
