# Generated by Django 6.0.4 on 2026-05-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_baihat_id_the_loai_baihat_the_loais'),
    ]

    operations = [
        migrations.AddField(
            model_name='nguoidung',
            name='spotify_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
