# Generated by Django 6.0.4 on 2026-05-20 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_nguoidung_spotify_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nguoidung',
            name='spotify_id',
        ),
    ]
