# Generated by Django 6.0.4 on 2026-05-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_nguoidung_spotify_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='baihat',
            name='thoi_luong',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['trang_thai', 'ngay_phat_hanh'], name='tbl_album_trang_t_42048a_idx'),
        ),
        migrations.AddIndex(
            model_name='baihat',
            index=models.Index(fields=['trang_thai', 'luot_nghe'], name='tbl_bai_hat_trang_t_688b9b_idx'),
        ),
        migrations.AddIndex(
            model_name='baihat',
            index=models.Index(fields=['trang_thai', 'nam_phat_hanh'], name='tbl_bai_hat_trang_t_1c9341_idx'),
        ),
        migrations.AddIndex(
            model_name='baihat',
            index=models.Index(fields=['quoc_gia'], name='tbl_bai_hat_quoc_gi_bc840b_idx'),
        ),
    ]
